from clases.cuentabancaria import *

print("Establecemos una cuenta bancaria con cambio a 1.38 y en euros")
micuenta = cuentabancaria("000000000012345", 1.38, 0)
micuenta.moneda_actual("e")
print("Ingresamos 250.5 euros y mostramos el saldo en ambas monedas")
micuenta.ingresar(250.5)
print(" - Cantidad en euros: ", micuenta.muestra_euros())
print(" - Cantidad en dólares: ", micuenta.muestra_dolares())
print("Ingresamos 125.75 euros y mostramos el saldo en ambas monedas")
micuenta.ingresar(125.75)
print(" - Cantidad en euros: ", micuenta.muestra_euros())
print(" - Cantidad en dólares: ", micuenta.muestra_dolares())
print("Cambiamos lal moneda actual a dólares")
micuenta.moneda_actual("d")
print("Retiramos 20 dólares y mostramos el saldo en ambas monedas")
micuenta.retirar(20)
print(" - Cantidad en euros: ", micuenta.muestra_euros())
print(" - Cantidad en dólares: ", micuenta.muestra_dolares())
