//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabloResultadoCalcMVC
    {
        public int ID_RESULTADO { get; set; }
        public int RESULTADO { get; set; }
    }
}
